### PR TITLE
Check LF for IMAP FETCH

### PR DESCRIPTION
**Pull request by tats**
cf. https://groups.google.com/g/mew-ja/c/6cTxl35J8s4

### CODE REVIEW

**Review by kazu-yamamoto — CHANGES_REQUESTED** [review]
I would like to have a comment to describe the intention of \n. 
Adding a referenece (https://groups.google.com/g/mew-ja/c/6cTxl35J8s4) would be good enough.

**Comment by tats** [comment]
I've improved the commit log with the reference, and force pushed.

**Comment by kazu-yamamoto** [comment]
Sorry but I cannot find your comment.

**Comment by tats** [comment]
The intention of "\n" is to certainly remove the matched line with "\n".

In mew-imap-filter(), if "\n" is not yet received, the problem occurs.
Because the line without "\n" is removed, but the next "\n" will remain
which causes blank line in the header.

See also the below removing part in mew-imap-filter().

```
       (when bytes
	 (goto-char (point-min))
	 (while (and (looking-at "^\\*") (= (forward-line) 0))
	   (delete-region (point-min) (point))))
```

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
Merged. Thank you for your contribution!

**Pull request merged**
