### PR TITLE
Prevent void function mew-match-string

### PR DESCRIPTION
**Pull request by tats**
Fix https://github.com/kazu-yamamoto/Mew/issues/180

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
I don't understand why this fixes the issue.
`mew-match-string` is used in other places of `mew-func.el`.
Why don't they harm?

**Comment by tats** [comment]
In other places of `mew-func.el`, `mew-match-string` is used in the
functions.  So, loading `mew-func.el` and then `mew-env.el` succeeded.

The problem is caused when `mew-match-string` is used at top-level
of `mew-func.el`.

Adding `(require 'mew-env)` to `mew-func.el` causes an infinite loop.
I didn't fight against the dependency hell, just avoided the problem.

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
I understand. Merged. Thanks.

**Pull request merged**
