### PR TITLE
Match exactly on an email address to specify a user ID to GnuPG

### PR DESCRIPTION
**Pull request by tats**
Patch to fix incorrect keys in encryption.

cf. https://github.com/kazu-yamamoto/Mew/issues/77

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Thank you for your contribution!

**Comment by tats** [comment]
For Debian 8 Jessie, this fix will be included in a point release,
though it isn't fixed through a security advisory.

**Comment by kazu-yamamoto** [comment]
Which security advisory are you talking about?

If you wish, I will release a new version.

**Comment by tats** [comment]
> Which security advisory are you talking about?

The Debian security team manages this problem as "Minor issue" and
"no-dsa (Debian Security Advisory)".

cf.
  - https://security-tracker.debian.org/tracker/TEMP-0784712-E83200
  - https://release.debian.org/proposed-updates/stable.html

> If you wish, I will release a new version.

It's nice anyway.

**Pull request merged**
