### PR TITLE
Add debug forms

### PR DESCRIPTION
**Pull request by mernst**

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
I don't know what the debug form is.
Would you tell me its manual?

**Comment by mernst** [comment]
Please see https://www.gnu.org/software/emacs/manual/html_node/elisp/Instrumenting-Macro-Calls.html

**Comment by kazu-yamamoto** [comment]
Thanks!
I have merged your PR.

**Comment by mernst** [comment]
Thanks!

**Pull request merged**
