### PR TITLE
Add GnuTLS support

### PR DESCRIPTION
**Pull request by tats**
cf. https://groups.google.com/g/mew-ja/c/sSfEPKD_CSM

Mew now supports GnuTLS library for TLS connections when the Emacs
is built with it.  To enable it, set mew-ssl-default to 'native.

mew-{imap,nntp,pop,smtp}-ssl now accept the following symbols:

- native - Use GnuTLS (this requires Emacs compiled with GnuTLS
         library).  When mew-smtp-ssl-port is equal to
         mew-smtp-port, a plain connection will be opened and
         upgraded by STARTTLS.
- tunnel - Use an external program to establish a TLS tunnel.
         stunnel(1) utility is used by default.

The value of mew-ssl-default is used when mew-{imap,nntp,pop,smtp}-ssl
is 't'.

### CODE REVIEW

**Comment by tats** [comment]
Also, experimental auth-source support is included.

Add mew-master-passwd-type, which specifies password manager
used when mew-use-master-passwd is non-nil.  'master and 'auth-source.

**Comment by kazu-yamamoto** [comment]
I'm now using this branch to see what will happen.

**Review by kazu-yamamoto — APPROVED** [review]
I don't find any issues so far.
So, let's merge this.

**Comment by kazu-yamamoto** [comment]
Merged. Thank you for your contributions!

**Comment by tats** [comment]
Thank you for merging.

FYI, for debugging the GnuTLS feature, increase gnutls-log-level and
look in the `*Messages*` buffer.  e.g. `(setq gnutls-log-level 2)`

**Pull request merged**
