### PR TITLE
Configure and Makefile

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
- updating configure.in by `autoupdate`
- renaming configure.in to configure.ac
- passing capital variables to call child Makefile

### CODE REVIEW

**Comment by tats** [comment]
I've skimmed through "GNU Coding Standards" and "GNU Make Manual".

cf.
  - GNU Coding Standards <https://www.gnu.org/prep/standards/>
> 7.2.5 Variables for Installation Directories
>    Installers are expected to override these values when calling 'make'
> (e.g., 'make prefix=/usr install') or 'configure' (e.g., 'configure
> --prefix=/usr').
>...
> 'bindir'
>...
  - GNU Make Manual <https://www.gnu.org/software/make/manual/>
> 6 How to Use Variables
>    It is traditional to use upper case letters in variable names, but we
> recommend using lower case letters for variable names that serve
> internal purposes in the makefile, and reserving upper case for
> parameters that control implicit rules or for parameters that the user
> should override with command options (*note Overriding Variables:
> Overriding.).

The variables `datadir`, `infodir`, `bindir` and `mandir` are GNU
standards that Makefiles should use to specify directories.  So,
capitalized standard variables would be a little confusable.

Though I don't have a strong objection with this.  If you reconsider
that these upper case redefinitions are still OK, I can accept that.

**Comment by kazu-yamamoto** [comment]
@tats Are you satisfied?

**Review by tats — APPROVED** [review]
Yes, let's merge this.

**Comment by kazu-yamamoto** [comment]
Merged. Thank you for reviewing!

**Pull request merged**
