### PR TITLE
mew-vars3.el: require mew-env so mew-face-spec-func is defined.

### PR DESCRIPTION
**Pull request by tdanckaert**
With this change, hopefully no more errors from native compilation.

### CODE REVIEW

**Comment by tats** [comment]
> mew-vars.el:

mew-vars3.el?

**Comment by tdanckaert** [comment]
You are right of course, I updated the commit!

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
Merged. Thanks!

**Pull request merged**
