### PR TITLE
getting only one Subject: on reply

### LINKED ISSUE #161: `Subject:` string gets doubled in reply
[mew 7ab02416029d0f15580efa3c4c3ff39f32d7c0ad]
[GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu,
 GTK+ Version 3.24.34, cairo version 1.16.0) of 2023-02-01]

Please consider the attached e-mail, generated by Thunderbird 102.6.0.  If I reply to that by pressing 'R', the subject fields gets doubled and looks like this:

```
Subject: Re: Tie not working as expected,Re: Tie not working as expected
```

It's very easy to miss that, not manually correcting it – I already got complaints.

It seems to me that Mew has difficulties with OpenPGP/MIME signed messages.  Maybe the simplest solution is to accept a single 'Subject' field only (namely the first)?

[problematic-email.txt](https://github.com/kazu-yamamoto/Mew/files/10555757/problematic-email.txt)

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
@lemzwerg @svenha This should fix #161.

### CODE REVIEW

**Comment by lemzwerg** [comment]
This works, thanks, but it isn't complete yet: If I press 'R' instead of 'r', the 'Subject:' line in the mail *body* still doubles the string.

**Comment by tats** [comment]
Also, forwarding is still problematic.
Adding workaround in mew-header-get-value may be enough.

**Comment by kazu-yamamoto** [comment]
`mew-header-get-value` is designed to correct multiple values.
I think it is caller's response to select one of them.
@tats What do you think?

**Comment by tats** [comment]
You are right, but it's just a workaround, and I think workaround in
mew-header-get-value should not be problematic.  I cannot imagine
handling doubled subject needed.

Instead, you may add workaround to mew-summary-forward() in mew-summary3.el
and mew-cite-get-value() in mew-draft.el, thouth a little complicated.

Both OK for me.

**Comment by tats** [comment]
Hmm, I found a similar issue when "Message-ID:" is in mew-cite-fields.

Should mew-header-get-value() correct multiple values **if allowed**?

**Comment by kazu-yamamoto** [comment]
According to RFC 5322, the following field should be one at most: orig-date, from, sender, reply-to, to, cc, bcc, message-id, in-reply-to, references, subject.

I would propose the following algorithm:

- `mew-header-get-value` checks if the arguments a member of the list above.
- If so, returns only one line.
- Otherwise, returns multiple lines, if any.

@tats What do you think?

**Comment by tats** [comment]
Looks fine.  Please go ahead.

**Comment by kazu-yamamoto** [comment]
I implemented this idea and did push -f. Please check.

**Comment by tats** [comment]
When "Message-ID:" is in mew-cite-fields, the value is doubled.

It should be checked with case insensitive.

**Comment by kazu-yamamoto** [comment]
That's caller's responsibility, again. If a caller use, for example, `mew-subj:`, it's fine.

**Comment by kazu-yamamoto** [comment]
@tats Nice catch! Done.

**Comment by kazu-yamamoto** [comment]
@tats May I merge this PR?

**Comment by tats** [comment]
Yes, let's merge this.  Thank you.

**Comment by kazu-yamamoto** [comment]
Merged. Thank you for reviewing!

**Pull request merged**
